/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Entry = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Text,
  'entryType' : IDL.Text,
  'endTime' : IDL.Text,
});
export const Machine = IDL.Record({
  'id' : IDL.Text,
  'entries' : IDL.Vec(Entry),
  'number' : IDL.Text,
});
export const Rates = IDL.Record({
  'bucket' : IDL.Float64,
  'breaker' : IDL.Float64,
});
export const Bill = IDL.Record({
  'id' : IDL.Text,
  'breakerTotalHours' : IDL.Float64,
  'customerName' : IDL.Text,
  'customerContact' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'bucketTotalHours' : IDL.Float64,
  'bucketTotalCost' : IDL.Float64,
  'amountPaid' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'paymentDate' : IDL.Opt(IDL.Text),
  'savedAt' : IDL.Int,
  'breakerTotalCost' : IDL.Float64,
  'machines' : IDL.Vec(Machine),
  'rates' : Rates,
  'dateOfWork' : IDL.Text,
});
export const PaymentReminder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'notes' : IDL.Text,
  'billNumber' : IDL.Text,
  'amountDue' : IDL.Float64,
  'billId' : IDL.Text,
});
export const Customer = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'createBill' : IDL.Func([Bill], [], []),
  'createReminder' : IDL.Func([PaymentReminder], [IDL.Bool], []),
  'deleteBill' : IDL.Func([IDL.Text], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteReminder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getRates' : IDL.Func([], [IDL.Opt(Rates)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(PaymentReminder)], ['query']),
  'getServerTime' : IDL.Func([], [IDL.Int], ['query']),
  'setRates' : IDL.Func([Rates], [], []),
  'updateBill' : IDL.Func([Bill], [], []),
  'upsertCustomer' : IDL.Func([Customer], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Entry = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Text,
    'entryType' : IDL.Text,
    'endTime' : IDL.Text,
  });
  const Machine = IDL.Record({
    'id' : IDL.Text,
    'entries' : IDL.Vec(Entry),
    'number' : IDL.Text,
  });
  const Rates = IDL.Record({ 'bucket' : IDL.Float64, 'breaker' : IDL.Float64 });
  const Bill = IDL.Record({
    'id' : IDL.Text,
    'breakerTotalHours' : IDL.Float64,
    'customerName' : IDL.Text,
    'customerContact' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'bucketTotalHours' : IDL.Float64,
    'bucketTotalCost' : IDL.Float64,
    'amountPaid' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'paymentDate' : IDL.Opt(IDL.Text),
    'savedAt' : IDL.Int,
    'breakerTotalCost' : IDL.Float64,
    'machines' : IDL.Vec(Machine),
    'rates' : Rates,
    'dateOfWork' : IDL.Text,
  });
  const PaymentReminder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'notes' : IDL.Text,
    'billNumber' : IDL.Text,
    'amountDue' : IDL.Float64,
    'billId' : IDL.Text,
  });
  const Customer = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    'createBill' : IDL.Func([Bill], [], []),
    'createReminder' : IDL.Func([PaymentReminder], [IDL.Bool], []),
    'deleteBill' : IDL.Func([IDL.Text], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteReminder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getRates' : IDL.Func([], [IDL.Opt(Rates)], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(PaymentReminder)], ['query']),
    'getServerTime' : IDL.Func([], [IDL.Int], ['query']),
    'setRates' : IDL.Func([Rates], [], []),
    'updateBill' : IDL.Func([Bill], [], []),
    'upsertCustomer' : IDL.Func([Customer], [], []),
  });
};

export const init = ({ IDL }) => { return []; };