/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : string,
  'breakerTotalHours' : number,
  'customerName' : string,
  'customerContact' : string,
  'paymentStatus' : string,
  'bucketTotalHours' : number,
  'bucketTotalCost' : number,
  'amountPaid' : number,
  'grandTotal' : number,
  'paymentDate' : [] | [string],
  'savedAt' : bigint,
  'breakerTotalCost' : number,
  'machines' : Array<Machine>,
  'rates' : Rates,
  'dateOfWork' : string,
}
export interface Customer {
  'contact' : string,
  'name' : string,
  'updatedAt' : bigint,
}
export interface Entry {
  'id' : string,
  'startTime' : string,
  'entryType' : string,
  'endTime' : string,
}
export interface Machine {
  'id' : string,
  'entries' : Array<Entry>,
  'number' : string,
}
export interface PaymentReminder {
  'id' : string,
  'customerName' : string,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'notes' : string,
  'billNumber' : string,
  'amountDue' : number,
  'billId' : string,
}
export interface Rates { 'bucket' : number, 'breaker' : number }
export interface _SERVICE {
  'createBill' : ActorMethod<[Bill], undefined>,
  'createReminder' : ActorMethod<[PaymentReminder], boolean>,
  'deleteBill' : ActorMethod<[string], undefined>,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteReminder' : ActorMethod<[string], boolean>,
  'getBills' : ActorMethod<[], Array<Bill>>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getRates' : ActorMethod<[], [] | [Rates]>,
  'getReminders' : ActorMethod<[], Array<PaymentReminder>>,
  'getServerTime' : ActorMethod<[], bigint>,
  'setRates' : ActorMethod<[Rates], undefined>,
  'updateBill' : ActorMethod<[Bill], undefined>,
  'upsertCustomer' : ActorMethod<[Customer], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];