/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PaymentReminder {
    id: string;
    customerName: string;
    createdAt: bigint;
    dueDate: bigint;
    notes: string;
    billNumber: string;
    amountDue: number;
    billId: string;
}
export interface Bill {
    id: string;
    breakerTotalHours: number;
    customerName: string;
    customerContact: string;
    paymentStatus: string;
    bucketTotalHours: number;
    bucketTotalCost: number;
    amountPaid: number;
    grandTotal: number;
    paymentDate?: string;
    savedAt: bigint;
    breakerTotalCost: number;
    machines: Array<Machine>;
    rates: Rates;
    dateOfWork: string;
}
export interface Entry {
    id: string;
    startTime: string;
    entryType: string;
    endTime: string;
}
export interface Rates {
    bucket: number;
    breaker: number;
}
export interface Customer {
    contact: string;
    name: string;
    updatedAt: bigint;
}
export interface Machine {
    id: string;
    entries: Array<Entry>;
    number: string;
}
export interface backendInterface {
    createBill(bill: Bill): Promise<void>;
    createReminder(reminder: PaymentReminder): Promise<boolean>;
    deleteBill(id: string): Promise<void>;
    deleteCustomer(nameContact: string): Promise<void>;
    deleteReminder(id: string): Promise<boolean>;
    getBills(): Promise<Array<Bill>>;
    getCustomers(): Promise<Array<Customer>>;
    getRates(): Promise<Rates | null>;
    getReminders(): Promise<Array<PaymentReminder>>;
    getServerTime(): Promise<bigint>;
    setRates(r: Rates): Promise<void>;
    updateBill(bill: Bill): Promise<void>;
    upsertCustomer(customer: Customer): Promise<void>;
}
import type { Bill as _Bill, Machine as _Machine, Rates as _Rates } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBill(arg0: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(to_candid_Bill_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(to_candid_Bill_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReminder(arg0: PaymentReminder): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(arg0);
            return result;
        }
    }
    async deleteBill(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteReminder(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async getBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBills();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBills();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getRates(): Promise<Rates | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRates();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRates();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminders(): Promise<Array<PaymentReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders();
            return result;
        }
    }
    async getServerTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getServerTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServerTime();
            return result;
        }
    }
    async setRates(arg0: Rates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRates(arg0);
            return result;
        }
    }
    async updateBill(arg0: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(to_candid_Bill_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(to_candid_Bill_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upsertCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertCustomer(arg0);
            return result;
        }
    }
}
function from_candid_Bill_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Rates]): Rates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    breakerTotalHours: number;
    customerName: string;
    customerContact: string;
    paymentStatus: string;
    bucketTotalHours: number;
    bucketTotalCost: number;
    amountPaid: number;
    grandTotal: number;
    paymentDate: [] | [string];
    savedAt: bigint;
    breakerTotalCost: number;
    machines: Array<_Machine>;
    rates: _Rates;
    dateOfWork: string;
}): {
    id: string;
    breakerTotalHours: number;
    customerName: string;
    customerContact: string;
    paymentStatus: string;
    bucketTotalHours: number;
    bucketTotalCost: number;
    amountPaid: number;
    grandTotal: number;
    paymentDate?: string;
    savedAt: bigint;
    breakerTotalCost: number;
    machines: Array<Machine>;
    rates: Rates;
    dateOfWork: string;
} {
    return {
        id: value.id,
        breakerTotalHours: value.breakerTotalHours,
        customerName: value.customerName,
        customerContact: value.customerContact,
        paymentStatus: value.paymentStatus,
        bucketTotalHours: value.bucketTotalHours,
        bucketTotalCost: value.bucketTotalCost,
        amountPaid: value.amountPaid,
        grandTotal: value.grandTotal,
        paymentDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.paymentDate)),
        savedAt: value.savedAt,
        breakerTotalCost: value.breakerTotalCost,
        machines: value.machines,
        rates: value.rates,
        dateOfWork: value.dateOfWork
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Bill_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Bill): _Bill {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    breakerTotalHours: number;
    customerName: string;
    customerContact: string;
    paymentStatus: string;
    bucketTotalHours: number;
    bucketTotalCost: number;
    amountPaid: number;
    grandTotal: number;
    paymentDate?: string;
    savedAt: bigint;
    breakerTotalCost: number;
    machines: Array<Machine>;
    rates: Rates;
    dateOfWork: string;
}): {
    id: string;
    breakerTotalHours: number;
    customerName: string;
    customerContact: string;
    paymentStatus: string;
    bucketTotalHours: number;
    bucketTotalCost: number;
    amountPaid: number;
    grandTotal: number;
    paymentDate: [] | [string];
    savedAt: bigint;
    breakerTotalCost: number;
    machines: Array<_Machine>;
    rates: _Rates;
    dateOfWork: string;
} {
    return {
        id: value.id,
        breakerTotalHours: value.breakerTotalHours,
        customerName: value.customerName,
        customerContact: value.customerContact,
        paymentStatus: value.paymentStatus,
        bucketTotalHours: value.bucketTotalHours,
        bucketTotalCost: value.bucketTotalCost,
        amountPaid: value.amountPaid,
        grandTotal: value.grandTotal,
        paymentDate: value.paymentDate ? candid_some(value.paymentDate) : candid_none(),
        savedAt: value.savedAt,
        breakerTotalCost: value.breakerTotalCost,
        machines: value.machines,
        rates: value.rates,
        dateOfWork: value.dateOfWork
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
